spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tododb?serverTimezone=Asia/Vladivostok
    username: root
    password: testtest
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

logbook:
  include:
    - /api/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 200
  write:
    chunk-size: 1000